In [1]:
import  numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
sentiment_score = pd.read_csv("sentiment_score.csv")

In [3]:
df=pd.read_csv("tmdb_8000_movies.csv")

In [4]:
df = df[df['id'].isin(sentiment_score['movie_id'])]

In [5]:
df.shape

(1934, 22)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1934 entries, 0 to 7860
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                1934 non-null   int64
 1   genres                1934 non-null   object
 2   homepage              1400 non-null   object
 3   id                    1934 non-null   int64
 4   keywords              1934 non-null   object
 5   original_language     1934 non-null   object
 6   original_title        1934 non-null   object
 7   overview              1934 non-null   object
 8   popularity            1934 non-null   float64
 9   production_companies  1934 non-null   object
 10  production_countries  1934 non-null   object
 11  release_date          1934 non-null   object
 12  revenue               1934 non-null   int64
 13  runtime               1934 non-null   int64
 14  spoken_languages      1934 non-null   object
 15  status                1934 non-null   object
 16  tagline               1896 non-null   object
 17  title                 1934 non-null   object
 18  vote_average          1934 non-null   float64
 19  vote_count            1934 non-null   int64
 20  cast                  1934 non-null   object
 21  crew                  1934 non-null   object
dtypes: float64(2), int64(5), object(15)
memory usage: 347.5+ KB

In [7]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'cast', 'crew'],
      dtype='object')

In [8]:
movies = df[['id','title','overview','genres','keywords','cast','crew']]

In [9]:
movies.head(1)

,id,title,overview,genres,keywords,cast,crew
0,1339713,Obsession,"After breaking the mysterious ""One Wish Willow...","[{""id"": 27, ""name"": ""Horror""}, {""id"": 53, ""nam...","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 615...","[{""adult"": false, ""gender"": 2, ""id"": 1561370, ...","[{""adult"": false, ""gender"": 2, ""id"": 2381985, ..."

In [10]:
movies.isnull().sum()

id          0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
movies.dropna(subset=["overview"], inplace=True)

In [12]:
movies.duplicated().sum()

0

In [13]:
movies.iloc[15].genres

'[{"id": 27, "name": "Horror"}, {"id": 9648, "name": "Mystery"}]'

In [14]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [15]:
movies['genres'].apply(convert)

0                           [Horror, Thriller]
1                  [Science Fiction, Thriller]
2       [Animation, Family, Comedy, Adventure]
3           [Horror, Mystery, Science Fiction]
4                                     [Comedy]
                         ...
7838        [Fantasy, Science Fiction, Comedy]
7844                 [Action, Thriller, Crime]
7851                        [Action, Thriller]
7855               [Fantasy, Action, Thriller]
7860                         [Comedy, Romance]
Name: genres, Length: 1934, dtype: object

In [16]:
movies['genres'] = movies['genres'].apply(convert)

In [17]:
movies.head(1)

,id,title,overview,genres,keywords,cast,crew
0,1339713,Obsession,"After breaking the mysterious ""One Wish Willow...","[Horror, Thriller]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 615...","[{""adult"": false, ""gender"": 2, ""id"": 1561370, ...","[{""adult"": false, ""gender"": 2, ""id"": 2381985, ..."

In [18]:
df['keywords'][0]

'[{"id": 1523, "name": "obsession"}, {"id": 6152, "name": "supernatural"}, {"id": 9712, "name": "possession"}, {"id": 4896, "name": "wish"}, {"id": 10048, "name": "unrequited love"}, {"id": 33494, "name": "couple"}, {"id": 214655, "name": "absurdism"}, {"id": 233130, "name": "self-harm"}, {"id": 256183, "name": "supernatural horror"}, {"id": 272553, "name": "psychological"}, {"id": 281237, "name": "independent film"}, {"id": 295907, "name": "psychological horror"}, {"id": 304115, "name": "cursed object"}]'

In [19]:
movies['keywords'] = movies['keywords'].apply(convert)

In [20]:
movies.head(1)

,id,title,overview,genres,keywords,cast,crew
0,1339713,Obsession,"After breaking the mysterious ""One Wish Willow...","[Horror, Thriller]","[obsession, supernatural, possession, wish, un...","[{""adult"": false, ""gender"": 2, ""id"": 1561370, ...","[{""adult"": false, ""gender"": 2, ""id"": 2381985, ..."

In [21]:
import json

In [22]:
def convert3(obj):
    L=[]
    counter = 0
    for i in json.loads(obj):
        if counter<3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [23]:
movies['cast'] = movies['cast'].apply(convert3)

In [24]:
movies.head(1)

,id,title,overview,genres,keywords,cast,crew
0,1339713,Obsession,"After breaking the mysterious ""One Wish Willow...","[Horror, Thriller]","[obsession, supernatural, possession, wish, un...","[Michael Johnston, Inde Navarrette, Cooper Tom...","[{""adult"": false, ""gender"": 2, ""id"": 2381985, ..."

In [25]:
def fetch_director(obj):
    L=[]
    for i in json.loads(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [26]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [27]:
movies.head(1)

,id,title,overview,genres,keywords,cast,crew
0,1339713,Obsession,"After breaking the mysterious ""One Wish Willow...","[Horror, Thriller]","[obsession, supernatural, possession, wish, un...","[Michael Johnston, Inde Navarrette, Cooper Tom...",[Curry Barker]

In [28]:
L1=[]
for i in movies['overview'][0].split():
        L1.append(i.replace('"',""))

In [29]:
movies["overview"] = movies["overview"].apply(lambda x: x.split())

In [30]:
movies['overview'].head()

0    [After, breaking, the, mysterious, "One, Wish,...
1    [A, cybersecurity, expert, becomes, a, whistle...
2    [When, Bonnie, receives, a, Lilypad, tablet, a...
3    [A, strange, doorway, appears, in, the, baseme...
4    [Twenty-six, years, after, outrunning, a, susp...
Name: overview, dtype: object

In [31]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,1339713,Obsession,"[After, breaking, the, mysterious, ""One, Wish,...","[Horror, Thriller]","[obsession, supernatural, possession, wish, un...","[Michael Johnston, Inde Navarrette, Cooper Tom...",[Curry Barker]
1,1275779,Disclosure Day,"[A, cybersecurity, expert, becomes, a, whistle...","[Science Fiction, Thriller]","[new york city, childhood trauma, alien, on th...","[Emily Blunt, Josh O'Connor, Colin Firth]",[Steven Spielberg]
2,1084244,Toy Story 5,"[When, Bonnie, receives, a, Lilypad, tablet, a...","[Animation, Family, Comedy, Adventure]","[farm, island, pig, horse, rescue mission, riv...","[Tom Hanks, Tim Allen, Joan Cusack]",[Andrew Stanton]
3,1083381,Backrooms,"[A, strange, doorway, appears, in, the, baseme...","[Horror, Mystery, Science Fiction]","[california, monster, therapist, surrealism, c...","[Chiwetel Ejiofor, Renate Reinsve, Mark Duplass]",[Kane Parsons]
4,1273221,Scary Movie,"[Twenty-six, years, after, outrunning, a, susp...",[Comedy],"[parody, sequel, slapstick comedy, crude humor...","[Marlon Wayans, Shawn Wayans, Anna Faris]",[Michael Tiddes]

In [32]:
movies["genres"] = movies["genres"].apply(lambda x: [i.replace(' ','') for i in x])
movies["keywords"] = movies["keywords"].apply(lambda x: [i.replace(' ','') for i in x])
movies["cast"] = movies["cast"].apply(lambda x: [i.replace(' ','') for i in x])
movies["crew"] = movies["crew"].apply(lambda x: [i.replace(' ','') for i in x])

In [33]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,1339713,Obsession,"[After, breaking, the, mysterious, ""One, Wish,...","[Horror, Thriller]","[obsession, supernatural, possession, wish, un...","[MichaelJohnston, IndeNavarrette, CooperTomlin...",[CurryBarker]
1,1275779,Disclosure Day,"[A, cybersecurity, expert, becomes, a, whistle...","[ScienceFiction, Thriller]","[newyorkcity, childhoodtrauma, alien, ontherun...","[EmilyBlunt, JoshO'Connor, ColinFirth]",[StevenSpielberg]
2,1084244,Toy Story 5,"[When, Bonnie, receives, a, Lilypad, tablet, a...","[Animation, Family, Comedy, Adventure]","[farm, island, pig, horse, rescuemission, riva...","[TomHanks, TimAllen, JoanCusack]",[AndrewStanton]
3,1083381,Backrooms,"[A, strange, doorway, appears, in, the, baseme...","[Horror, Mystery, ScienceFiction]","[california, monster, therapist, surrealism, c...","[ChiwetelEjiofor, RenateReinsve, MarkDuplass]",[KaneParsons]
4,1273221,Scary Movie,"[Twenty-six, years, after, outrunning, a, susp...",[Comedy],"[parody, sequel, slapstickcomedy, crudehumor, ...","[MarlonWayans, ShawnWayans, AnnaFaris]",[MichaelTiddes]

In [34]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [35]:
movies.head()

,id,title,overview,genres,keywords,cast,crew,tags
0,1339713,Obsession,"[After, breaking, the, mysterious, ""One, Wish,...","[Horror, Thriller]","[obsession, supernatural, possession, wish, un...","[MichaelJohnston, IndeNavarrette, CooperTomlin...",[CurryBarker],"[After, breaking, the, mysterious, ""One, Wish,..."
1,1275779,Disclosure Day,"[A, cybersecurity, expert, becomes, a, whistle...","[ScienceFiction, Thriller]","[newyorkcity, childhoodtrauma, alien, ontherun...","[EmilyBlunt, JoshO'Connor, ColinFirth]",[StevenSpielberg],"[A, cybersecurity, expert, becomes, a, whistle..."
2,1084244,Toy Story 5,"[When, Bonnie, receives, a, Lilypad, tablet, a...","[Animation, Family, Comedy, Adventure]","[farm, island, pig, horse, rescuemission, riva...","[TomHanks, TimAllen, JoanCusack]",[AndrewStanton],"[When, Bonnie, receives, a, Lilypad, tablet, a..."
3,1083381,Backrooms,"[A, strange, doorway, appears, in, the, baseme...","[Horror, Mystery, ScienceFiction]","[california, monster, therapist, surrealism, c...","[ChiwetelEjiofor, RenateReinsve, MarkDuplass]",[KaneParsons],"[A, strange, doorway, appears, in, the, baseme..."
4,1273221,Scary Movie,"[Twenty-six, years, after, outrunning, a, susp...",[Comedy],"[parody, sequel, slapstickcomedy, crudehumor, ...","[MarlonWayans, ShawnWayans, AnnaFaris]",[MichaelTiddes],"[Twenty-six, years, after, outrunning, a, susp..."

In [36]:
new_df = movies[['id','title','tags']]
new_df.head()

        id           title                                               tags
0  1339713       Obsession  [After, breaking, the, mysterious, "One, Wish,...
1  1275779  Disclosure Day  [A, cybersecurity, expert, becomes, a, whistle...
2  1084244     Toy Story 5  [When, Bonnie, receives, a, Lilypad, tablet, a...
3  1083381       Backrooms  [A, strange, doorway, appears, in, the, baseme...
4  1273221     Scary Movie  [Twenty-six, years, after, outrunning, a, susp...

In [37]:
new_df.rename(columns={'id': 'movie_id'}, inplace=True)

In [38]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [39]:
new_df.head()

   movie_id           title                                               tags
0   1339713       Obsession  After breaking the mysterious "One Wish Willow...
1   1275779  Disclosure Day  A cybersecurity expert becomes a whistleblower...
2   1084244     Toy Story 5  When Bonnie receives a Lilypad tablet as a gif...
3   1083381       Backrooms  A strange doorway appears in the basement of a...
4   1273221     Scary Movie  Twenty-six years after outrunning a suspicious...

In [40]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [41]:
import nltk

In [42]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [43]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [44]:
new_df['tags'] = new_df['tags'].apply(stem)

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=5000,stop_words='english')

In [59]:
vectors = tfidf.fit_transform(new_df['tags']).toarray()

In [60]:
vectors[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [61]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zombieapocalyps', 'zombies', 'zone'],
      dtype=object)

In [62]:
from sklearn.metrics.pairwise import cosine_similarity

In [63]:
similarity = cosine_similarity(vectors)

In [64]:
similarity.shape

(1934, 1934)

In [65]:
similarity[1]

array([0.00511771, 1.        , 0.02076694, ..., 0.00597623, 0.02163532,
       0.01792525])

In [66]:
movies = new_df.merge(sentiment_score,on='movie_id',how='left')

In [67]:
movies.head()

,movie_id,title,tags,sentiment_score
0,1339713,Obsession,"after break the mysteri ""one wish willow"" to w...",0.433956
1,1275779,Disclosure Day,a cybersecur expert becom a whistleblow after ...,0.363761
2,1084244,Toy Story 5,when bonni receiv a lilypad tablet as a gift a...,0.620621
3,1083381,Backrooms,a strang doorway appear in the basement of a f...,0.483417
4,1273221,Scary Movie,twenty-six year after outrun a suspici familia...,0.460480

In [68]:
def recommend(movie,alpha=0.8):
    movie_index = movies[movies['title']==movie].index[0]
    distances = similarity[movie_index]

    recommendation = []

    for idx,sim_score in enumerate(distances):
        if idx==movie_index:
            continue
        sentiment = movies.iloc[idx]['sentiment_score']
        final_score = alpha * sim_score + (1 - alpha) * sentiment
        recommendation.append((idx,final_score))
    
    movies_list = sorted(recommendation,reverse=True,key = lambda x:x[1])[1:6]

    
    for idx,final_score in movies_list:
        print(movies.iloc[idx].title)

In [69]:
recommend('Obsession')

Three Thousand Years of Longing
The Firm
You're Next
Aladdin
13 Going on 30

In [57]:
import pickle
pickle.dump(movies,open('movies.pkl','wb'))